
platform :ios, '12.0'
inhibit_all_warnings!
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'HuanChengSDK' do

pod 'MBProgressHUD'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'Masonry'
pod 'MJRefresh'
pod 'MJExtension'
pod 'IQKeyboardManager'
pod 'ReactiveObjC'
pod 'CYLTabBarController'
end

# Xcode 14 pod 默认需要签名  此处 在 pod install 时改为不签名
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
